apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flaskapp
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flaskapp
          image: docker.io/pioneerfromussr/flaskapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
